permalink: /posts/:title
rdiscount:
  extensions: [smart]
name: Rotem Hermon
site_name: dev/space - Rotem Hermon
url: http://rore.im
description: Rotem Hermon's dev space
twitter: margolis20
linkedin: http://il.linkedin.com/in/rotemhermon/
github: rore
gravatar_url: https://s.gravatar.com/avatar/ed52a75c8cf2f4cb1c2e9d8d161ca771
safe: true
lsi: false
markdown: redcarpet
highlighter: rouge
