permalink: /posts/:title
markdown: kramdown
kramdown:
  input: GFM
name: Rotem Hermon
site_name: dev/space - Rotem Hermon
url: https://rore.im
description: Rotem Hermon's dev space
twitter: margolis20
linkedin: https://il.linkedin.com/in/rotemhermon/
github: rore
avatar_url: /images/avatar.jpg
safe: true
lsi: false
highlighter: rouge